FROM node:14.17.5

WORKDIR /usr/src/app
COPY package*.json ./
COPY ./src src
COPY tsconfig.json .
RUN npm install && npm run build && rm -rf node_modules && npm install --production

ENTRYPOINT ["node"]
CMD ["build/src/index.js"]
