apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-services-counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-services-counter
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backend-services-counter
        tier: node
    spec:
      containers:
        - name: backend-services-counter
          image: gcr.io/private-260418/counter:latest
          env:
            - name: DEPLOY_TIME
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-credentials-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-credentials-db
                  key: password
            - name: DB_DB
              value: "counter"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-credentials-db
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-credentials-db
                  key: db_port
            - name: REST_PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "30"
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          args: []

        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.14
          # [START cloudsql_security_context]
          securityContext:
            runAsUser: 2  # non-root user
            allowPrivilegeEscalation: false
          # [END cloudsql_security_context]
          volumeMounts:
            - name: proxy-credentials-db
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: proxy-credentials-db
          secret:
            secretName: proxy-credentials-db

    # [END volumes] ,