apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-services-counter
spec:
  template:
    spec:
      containers:
        - name: backend-services-counter
          env:
            - name: GQL_INTROSPECTION
              value: "1"
            - name: GQL_PLAYGROUND
              value: "1"
        - name: cloudsql-proxy
          command: ["/cloud_sql_proxy",
                    "-instances=private-260418:europe-west1:dev-counter1-db=tcp:5432",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
