---
apiVersion: v1
kind: Service
metadata:
  name: backend-services-counter-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: backend-services-counter